### ISSUE TITLE
TOPICOS AVANZADOS_PRACTICA 9_MARIA JOSE LOPEZ LEYVA_LITZY LOPEZ LOPEZ_ JUDITH REYNA CRUZ SANTIAGO

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-topicos-avanzados#1]
[TOPICOS AVANZADOS_PRACTICA 9_MARIA JOSE LOPEZ LEYVA_LITZY LOPEZ LOPEZ_ JUDITH REYNA CRUZ SANTIAGO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-topicos-avanzados/files/8734578/TOPICOS.AVANZADOS_PRACTICA.9_MARIA.JOSE.LOPEZ.LEYVA_LITZY.LOPEZ.LOPEZ_.JUDITH.REYNA.CRUZ.SANTIAGO.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
